version: '3.2'

services:
  image_format_converter:
    image: 'image_format_converter:2.5'
    container_name: imageformatconverter_image_format_converter_1
    env_file: '.env'
    volumes:
      - 'sceti-completed:/sceti-completed'
      - 'sceti-completed-2:/sceti-completed-2'
      - 'sceti-completed-3:/sceti-completed-3'
      - 'sceti-completed-4:/sceti-completed-4'

volumes:
  sceti-completed:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${SC_1_ADDRPERMS}
      device: ":${SC_1_DEVICE}"
  sceti-completed-2:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${SC_2_ADDRPERMS}
      device: ":${SC_2_DEVICE}"
  sceti-completed-3:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${SC_3_ADDRPERMS}
      device: ":${SC_3_DEVICE}"
  sceti-completed-4:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${SC_4_ADDRPERMS}
      device: ":${SC_4_DEVICE}"
